export const shopActionType = {
  ADD_ITEM: "ADD_ITEM",
  INCREASE_ITEM_QUANTITY: "INCREASE_ITEM_QUANTITY",
  DECREASE_ITEM_QUANTITY: "DECREASE_ITEM_QUANTITY",
  TOTAL_AMOUNT: "TOTAL_AMOUNT",
  FELTER_ITEM: "FELTER_ITEM",
};
